server.port=9090

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

logging.level.org.springframework.orm.jpa=INFO
logging.level.org.springframework.transaction=INFO
logging.level.org.springframework.transaction.interceptor=TRACE
logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG

# TODO Append connection to Postgres DB
#docker run --name shareit-db -p 5432:5432 -e POSTGRES_DB=shareit -e POSTGRES_USER=dbuser -e POSTGRES_PASSWORD=12345 -d postgres:16
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
spring.datasource.username=dbuser
spring.datasource.password=12345
